spring:
  profiles:
    active: default
  application:
    name: challenge-api
  datasource:
    hikari:
      password: ${PASSWORD}
      username: ${USERNAME}
      max-lifetime: 45000
      idle-timeout: 35000
    url: ${URL_DATABASE}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      client:
        max-uri-tags: 950
      server:
        max-uri-tags: 950
  endpoints:
    web:
      exposure:
        include: metrics, health
server:
  port: ${PORT}
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024