spring:
  profiles:
    active: default
  application:
    name: challenge-api
  datasource:
    url: ${JDBC_DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true