spring:
  application:
    name: challenge-api
  datasource:
    hikari:
      password: 21db20c2f57d3fe8ed75e5a978864198eeb0d8c0325e30a1242ae5acfa43428b
      username: phdapeuagtjgjm
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-35-175-155-248.compute-1.amazonaws.com:5432/d46pjg9qmtv12a
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true