DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS product;

CREATE TABLE stock (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  items INT NOT NULL,
  priceStock DECIMAL NOT NULL,
  createdAt VARCHAR NOT NULL
);

CREATE TABLE product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  unitPrice DECIMAL NOT NULL,
  quantity INT NOT NULL
);